import os
import shutil
import subprocess
import sys
import time

from setuptools import setup, Extension
from setuptools.command.build_ext import build_ext

# ---------------------------------------------------------------------------
# liburing
#
# The truenas_os io_uring binding is built against upstream liburing rather than
# the Debian package: trixie ships 2.9, which predates the 6.18 additions it
# relies on (IORING_REGISTER_QUERY, IORING_ENTER_NO_IOWAIT, READV_FIXED).
# The tree is cloned at build time from a pinned tag instead of being vendored
# into this repo, so no third-party source is carried here and no
# Build-Depends / runtime .so dependency is added.
#
# LIBURING_COMMIT is the real pin -- a tag is mutable, a sha is not.
# ---------------------------------------------------------------------------
LIBURING_URL = 'https://github.com/axboe/liburing.git'
LIBURING_TAG = 'liburing-2.15'
LIBURING_COMMIT = 'd41bf9220ec39277ff235379e9089d9e0fd6c2a5'
LIBURING_DIR = os.path.join('build', 'liburing')
LIBURING_SRC_ENV = 'TRUENAS_PYOS_LIBURING_SRC'

# The shallow clone is the one build step that reaches the network; a github
# hiccup or rate-limit should not fail the build on the first attempt.
LIBURING_CLONE_RETRIES = 3

# The liburing *library* is exactly these; nolibc.c, sanitize.c and ffi.c are
# conditional in src/Makefile and are not wanted here.  nolibc.c in particular
# is only for the -nostdlib -ffreestanding build, which a CPython extension
# must never be -- hence ./configure --use-libc below.
LIBURING_SOURCES = [
    'setup.c',
    'queue.c',
    'register.c',
    'syscall.c',
    'version.c',
]

# Generated by ./configure; the build cannot proceed without them.
LIBURING_GENERATED = [
    ('config-host.h',),
    ('src', 'include', 'liburing', 'compat.h'),
    ('src', 'include', 'liburing', 'io_uring_version.h'),
]


def _git(args, tree=None):
    argv = ['git']
    if tree is not None:
        argv += ['-C', tree]
    argv += args
    out = subprocess.run(argv, check=True, capture_output=True, text=True)
    return out.stdout.strip()


def _clone_liburing(tree):
    """Shallow-clone the pinned tag into `tree`, retrying transient failures.

    A --depth 1 clone is a single network fetch with nothing to resume, so a
    failure is retried from scratch: the partial tree (a failed clone can leave
    a non-empty directory the next attempt would refuse) is discarded and the
    clone re-run after a short backoff.
    """
    for attempt in range(1, LIBURING_CLONE_RETRIES + 1):
        try:
            _git(['clone', '--depth', '1', '--branch', LIBURING_TAG,
                  LIBURING_URL, tree])
            return
        except subprocess.CalledProcessError as exc:
            if os.path.isdir(tree):
                shutil.rmtree(tree)
            if attempt == LIBURING_CLONE_RETRIES:
                raise
            print('liburing clone failed (attempt %d/%d), retrying: %s'
                  % (attempt, LIBURING_CLONE_RETRIES,
                     (exc.stderr or '').strip()),
                  file=sys.stderr)
            time.sleep(2 * attempt)


def _liburing_configured(tree):
    """True if `tree` is already configured the way this build needs.

    Existence of the generated headers is not sufficient -- their *content*
    matters.  A tree configured without --use-libc (upstream's default on
    x86-64, aarch64 and riscv64) defines CONFIG_NOLIBC, which switches
    liburing's lib.h/syscall.h to the freestanding __uring_malloc/__uring_free/
    __uring_memset shims.  Those live in nolibc.c, which this build
    deliberately does not compile.

    That combination does not fail the build: shared objects tolerate
    undefined symbols, so it links cleanly and then dies at import with
    "undefined symbol: __uring_free".  Catch it here instead.
    """
    generated = [os.path.join(tree, *parts) for parts in LIBURING_GENERATED]
    if not all(os.path.exists(path) for path in generated):
        return False

    with open(os.path.join(tree, 'config-host.h')) as fp:
        if 'CONFIG_NOLIBC' in fp.read():
            return False

    return True


def _configure_liburing(tree):
    """Generate config-host.h and the two liburing/*.h headers.

    --use-libc suppresses CONFIG_NOLIBC.  Without it, configure enables the
    freestanding build, which requires nolibc.c and -nostdlib -nodefaultlibs
    -ffreestanding -- none of which is compatible with linking into a CPython
    extension.
    """
    if _liburing_configured(tree):
        return

    subprocess.run(['./configure', '--use-libc'], cwd=tree, check=True)

    missing = [
        os.path.join(tree, *parts) for parts in LIBURING_GENERATED
        if not os.path.exists(os.path.join(tree, *parts))
    ]
    if missing:
        raise SystemExit(
            'liburing ./configure did not generate: %s' % ', '.join(missing)
        )

    if not _liburing_configured(tree):
        raise SystemExit(
            'liburing in %s is configured with CONFIG_NOLIBC even after '
            './configure --use-libc. Building against it would produce a '
            'module that links but fails at import with "undefined symbol: '
            '__uring_free". Remove the tree (or unset %s) and let the build '
            'clone a fresh one.' % (tree, LIBURING_SRC_ENV)
        )


def fetch_liburing():
    """Return a path to a configured liburing tree at LIBURING_COMMIT."""
    override = os.environ.get(LIBURING_SRC_ENV)
    if override:
        # Offline / air-gapped builds pre-seed the tree and point us at it.
        # The commit is not checked here: the builder chose this tree
        # explicitly, and it may legitimately be an export without .git.
        tree = os.path.abspath(override)
        if not os.path.isdir(tree):
            raise SystemExit(
                '%s=%s is not a directory' % (LIBURING_SRC_ENV, override)
            )
        _configure_liburing(tree)
        return tree

    tree = os.path.abspath(LIBURING_DIR)

    # Idempotent: a tree already at the pinned commit is reused as-is, so
    # repeated build_ext runs do not re-clone.  Anything else is discarded
    # rather than fetched into -- a shallow clone has no history to move
    # through, and a stale tree is not worth repairing.
    if os.path.isdir(os.path.join(tree, '.git')):
        try:
            current = _git(['rev-parse', 'HEAD'], tree=tree)
        except subprocess.CalledProcessError:
            current = None
        if current != LIBURING_COMMIT:
            shutil.rmtree(tree)

    if not os.path.isdir(tree):
        parent = os.path.dirname(tree)
        if parent:
            os.makedirs(parent, exist_ok=True)
        _clone_liburing(tree)

    head = _git(['rev-parse', 'HEAD'], tree=tree)
    if head != LIBURING_COMMIT:
        raise SystemExit(
            'liburing %s resolved to %s, expected %s -- refusing to build '
            'against an unexpected tree' % (LIBURING_TAG, head, LIBURING_COMMIT)
        )

    _configure_liburing(tree)
    return tree


class build_ext_with_liburing(build_ext):
    """Materialise liburing before compiling, and wire it into truenas_os.

    setuptools resolves Extension.sources at build_ext time, so extending them
    here is well-defined -- and it keeps the clone out of the import-time path
    of setup.py, which runs for every metadata query.
    """

    def run(self):
        for ext in self.extensions:
            if ext.name != 'truenas_os':
                continue
            tree = fetch_liburing()
            ext.sources += [
                os.path.join(tree, 'src', src) for src in LIBURING_SOURCES
            ]
            ext.include_dirs += [os.path.join(tree, 'src', 'include')]
            # LIBURING_INTERNAL applies to the whole extension so that
            # io_uring_get_sqe() resolves to the single out-of-line definition
            # in queue.c rather than being inlined in our translation units
            # and extern in liburing's.
            ext.define_macros += [
                ('_GNU_SOURCE', None),
                ('LIBURING_INTERNAL', None),
            ]
            ext.extra_compile_args += [
                '-include', os.path.join(tree, 'config-host.h'),
            ]
        super().run()


truenas_os_ext = Extension(
    'truenas_os',
    sources=[
        'src/cext/os/open_by_mnt.c',
        'src/cext/os/truenas_os.c',
        'src/cext/os/fhandle.c',
        'src/cext/os/mount.c',
        'src/cext/os/iter_mount.c',
        'src/cext/os/statx.c',
        'src/cext/os/openat2.c',
        'src/cext/os/open_tree.c',
        'src/cext/os/move_mount.c',
        'src/cext/os/mount_setattr.c',
        'src/cext/os/fsmount.c',
        'src/cext/os/umount2.c',
        'src/cext/os/userns.c',
        'src/cext/os/acl_check.c',
        'src/cext/os/renameat2.c',
        'src/cext/os/fsiter.c',
        'src/cext/os/acl.c',
        'src/cext/os/util_enum.c',
        'src/cext/os/nfs4acl.c',
        'src/cext/os/posixacl.c',
        'src/cext/os/xattr.c',
        # io_uring binding -- the truenas_os.Uring / UringOp types, compiled
        # into this same shared object as top-level types (not a submodule).
        # uring.c: the Uring/UringOp types, the prep_* / submit / reap / cancel
        # stubs, and the ring lifecycle; submitreap.c: the submit and reap
        # mechanics behind those stubs; openclose.c + rw.c + stat.c: the prep_*
        # op workers; op.h (static inline) holds the op-slot state machine shared
        # across them.
        'src/cext/uring/uring.c',
        'src/cext/uring/submitreap.c',
        'src/cext/uring/openclose.c',
        'src/cext/uring/rw.c',
        'src/cext/uring/stat.c',
    ],
    include_dirs=['src/cext/os', 'src/cext/uring']
)

truenas_pyfilter_ext = Extension(
    'truenas_pyfilter',
    sources=[
        'src/cext/filter_utils/truenas_pyfilter.c',
        'src/cext/filter_utils/filter_list.c',
        'src/cext/filter_utils/filter_options.c',
    ],
    include_dirs=['src/cext/filter_utils'],
    extra_compile_args=['-O2', '-Wall', '-Wextra', '-Wno-unused-parameter'],
)

# 'python3 setup.py fetch-liburing' materialises the pinned liburing tree and
# exits, without running the build. A Debian build calls this from an earlier,
# network-enabled phase (debian/rules override_dh_auto_configure); the sandboxed
# wheel-build phase then reuses the tree -- build_ext's fetch_liburing() finds
# build/liburing at the pinned commit and skips the clone.
if sys.argv[1:] == ['fetch-liburing']:
    fetch_liburing()
    sys.exit(0)

setup(
    cmdclass={'build_ext': build_ext_with_liburing},
    ext_modules=[truenas_os_ext, truenas_pyfilter_ext],
    packages=[
        'truenas_os',
        'truenas_pyfilter',
        '_truenas_os_scripts',
        'truenas_os_pyutils',
        'truenas_os_pyutils.truenas_shutil',
    ],
    package_dir={
        'truenas_os': 'stubs/truenas_os',
        'truenas_pyfilter': 'stubs/truenas_pyfilter',
        '_truenas_os_scripts': 'scripts',
        'truenas_os_pyutils': 'src/truenas_os_pyutils',
        'truenas_os_pyutils.truenas_shutil': 'src/truenas_os_pyutils/truenas_shutil',
    },
    package_data={
        'truenas_os': ['*.pyi', 'py.typed'],
        'truenas_pyfilter': ['*.pyi', 'py.typed'],
        'truenas_os_pyutils': ['py.typed'],
    },
    entry_points={
        'console_scripts': [
            'truenas_getfacl=_truenas_os_scripts._getfacl:main',
            'truenas_setfacl=_truenas_os_scripts._setfacl:main',
        ],
    },
)
