"""Per-thread CPU usage from a BPF task iterator."""

from types import TracebackType
from typing import Any, ClassVar, final

@final
class ThreadStat(tuple[Any, ...]):  # PyStructSequence, not a true NamedTuple
    """Statistics for one thread."""
    n_fields: ClassVar[int]
    n_sequence_fields: ClassVar[int]
    n_unnamed_fields: ClassVar[int]
    __match_args__: ClassVar[tuple[str, ...]]
    def __replace__(self, /, **changes: Any) -> ThreadStat: ...
    @property
    def tid(self) -> int: ...
    @property
    def tgid(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def process_name(self) -> str: ...
    @property
    def state(self) -> str: ...
    @property
    def cpu(self) -> int: ...
    @property
    def cpu_ns(self) -> int: ...
    @property
    def exited_cpu_ns(self) -> int: ...
    @property
    def wait_ns(self) -> int: ...
    @property
    def rss(self) -> int | None: ...

@final
class ThreadSample(tuple[Any, ...]):  # PyStructSequence, not a true NamedTuple
    """Result of ThreadSampler.sample()."""
    n_fields: ClassVar[int]
    n_sequence_fields: ClassVar[int]
    n_unnamed_fields: ClassVar[int]
    __match_args__: ClassVar[tuple[str, ...]]
    def __replace__(self, /, **changes: Any) -> ThreadSample: ...
    @property
    def elapsed_ns(self) -> int: ...
    @property
    def threads(self) -> list[ThreadStat]: ...

@final
class ThreadSampler:
    """Load the BPF thread iterator and take a baseline snapshot."""
    def __new__(cls) -> ThreadSampler: ...
    def sample(self, *, include_idle: bool = False) -> ThreadSample: ...
    def close(self) -> None: ...
    def __enter__(self) -> ThreadSampler: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
        /,
    ) -> None: ...
